# Generated by Django 4.1.13 on 2023-12-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_tema_remove_pregunta_cursos_pregunta_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='temas',
            field=models.ManyToManyField(blank=True, to='cursos.tema'),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
