# Generated by Django 4.1.13 on 2023-12-06 22:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_temas_delete_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('pieImagen', models.CharField(max_length=400)),
                ('concepto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
            ],
        ),
    ]
