# Generated by Django 4.1.13 on 2023-12-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_contenidocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidocurso',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='cursos.curso'),
        ),
    ]
