# Generated by Django 4.1.13 on 2023-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camarita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_1', models.CharField(max_length=100)),
                ('campo_2', models.CharField(max_length=100)),
            ],
        ),
    ]
