# Generated by Django 4.1.13 on 2023-11-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaraComercio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camarita',
            old_name='campo_1',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='camarita',
            old_name='campo_2',
            new_name='titulo',
        ),
    ]
